version: "2"

services:

  mamute:
    build:
      context: "services/mamute"
    # environment:
      # MAIL_SERVER: 
      # MAIL_PORT: 
      # MAIL_USE_TLS: "true"
      # MAIL_USERNAME: 
      # MAIL_PASSWORD: 
      # MAIL_FROM_NAME: "Mahisoft Mamute"
      # MAIL_FROM: "no-reply@mahisoft.com"
    links:
      - "mysql"
    restart: "always"

  mysql:
    build:
      context: "services/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mamute"
      MYSQL_USER: "mamute"
      MYSQL_PASSWORD: "mamute"
    restart: "always"
    volumes:
      - "./data/mysql:/var/lib/mysql"
