version: "2"

services:

  mamute:
    environment:
      MAMUTE_HOST: "https://km.mahisoft.com"

  haproxy:
    image: "bradjonesllc/docker-haproxy-letsencrypt"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "mamute:www"
    environment:
      CERTS: "km.mahisoft.com"
      EMAIL: "mgomez@mahisoft.com"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"

  netdata:
    image: "titpetric/netdata"
    restart: "always"
    network_mode: "host"
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
