version: "2"

services:

  mamute:
    environment:
      MAMUTE_ADDRESS: "https://km.mahisoft.com"
      MAMUTE_FEATURE_GOOGLE_LOGIN: "true"

  haproxy:
    build:
      context: "services/haproxy"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "mamute:www"
    environment:
      CERTS: "km.mahisoft.com"
      EMAIL: "mgomez@mahisoft.com"
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"
