version: "2"

services:

  mamute:
    image: "mgomezch/mamute"
    env_file:
      - "services/mamute/.env"
    # environment:
      # MAMUTE_MAIL_ADDRESS: 
      # MAMUTE_MAIL_USE_TLS: "true"
      # MAMUTE_MAIL_FROM: "no-reply@mahisoft.com"
      # MAMUTE_MAIL_FROM_NAME: "Mahisoft Mamute"
    links:
      - "mysql"
    restart: "always"
    volumes:
      - "./data/mamute/attachments:/var/lib/mamute/attachments"

  mysql:
    build:
      context: "services/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mamute"
      MYSQL_USER: "mamute"
      MYSQL_PASSWORD: "mamute"
    restart: "always"
    volumes:
      - "./data/mysql:/var/lib/mysql"
