version: "2"

services:

  mamute:
    image: "mgomezch/mamute"
    env_file:
      - "services/mamute/.env"
    environment:
      MAMUTE_PORT: 80
      # MAIL_SERVER: 
      # MAIL_PORT: 
      # MAIL_USE_TLS: "true"
      # MAIL_FROM_NAME: "Mahisoft Mamute"
      # MAIL_FROM: "no-reply@mahisoft.com"
    links:
      - "mysql"
    restart: "always"
    volumes:
      - "./data/mamute/attachments:/var/lib/mamute/attachments"

  mysql:
    build:
      context: "services/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mamute"
      MYSQL_USER: "mamute"
      MYSQL_PASSWORD: "mamute"
    restart: "always"
    volumes:
      - "./data/mysql:/var/lib/mysql"
